import Link from 'next/link'

export default function DisclaimerPage() {
  return (
    <main style={{ maxWidth: 680, margin: '0 auto', padding: '2rem 1rem' }}>
      <div style={{ marginBottom: '2rem' }}>
        <Link href="/" style={{ fontSize: 13, color: '#888', textDecoration: 'none' }}>← Back</Link>
      </div>

      <div style={{ fontSize: 20, fontWeight: 500, letterSpacing: '-0.5px', color: '#111', marginBottom: 32 }}>
        Sort<span style={{ color: '#e53935' }}>Japan</span>
      </div>

      <h1 style={{ fontSize: 26, fontWeight: 500, color: '#111', marginBottom: 8 }}>Disclaimer</h1>
      <p style={{ fontSize: 13, color: '#aaa', marginBottom: 32 }}>Last updated: April 2026</p>

      <div style={{ fontSize: 15, lineHeight: 1.8, color: '#444' }}>

        <Section title="1. For informational purposes only">
          The document analysis provided by SortJapan is generated by artificial intelligence and is intended solely for general informational purposes. It does not constitute legal, financial, tax, or professional advice of any kind.
        </Section>

        <Section title="2. No guarantee of accuracy">
          While we strive to provide helpful and accurate analysis, SortJapan makes no warranties or representations regarding the completeness, accuracy, or reliability of any information provided. AI-generated content may contain errors, omissions, or outdated information.
        </Section>

        <Section title="3. Always verify with official sources">
          Before taking any action based on information provided by SortJapan — including but not limited to making payments, filing documents, or contacting government offices — you must verify the information with the relevant official authority, such as your local city hall (市役所), the Immigration Services Agency (出入国在留管理庁), or a qualified professional (行政書士, 弁護士, 税理士).
        </Section>

        <Section title="4. Not a substitute for professional advice">
          SortJapan is not a law firm, accounting firm, or immigration consultancy. The use of this service does not create any attorney-client, advisor-client, or professional relationship between you and SortJapan.
        </Section>

        <Section title="5. Limitation of liability">
          To the fullest extent permitted by applicable law, SortJapan and its operators shall not be liable for any direct, indirect, incidental, consequential, or special damages arising from your use of or reliance on this service, including any actions taken based on document analysis provided.
        </Section>

        <Section title="6. Document content">
          You are responsible for ensuring that any documents you upload do not contain sensitive personal information beyond what is necessary for analysis. Do not upload documents containing bank account numbers, passwords, or third-party personal information without their consent.
        </Section>

        <Section title="7. Changes to this disclaimer">
          We reserve the right to update this disclaimer at any time. Continued use of the service following any changes constitutes your acceptance of the updated disclaimer.
        </Section>

        <div style={{ marginTop: 32, padding: '16px', background: '#fff8e1', borderRadius: 10, border: '1px solid #ffe082', fontSize: 14, color: '#856404' }}>
          ⚠️ In plain English: Our AI helps you understand Japanese documents, but please always double-check with the relevant office before doing anything important. We're a tool to help you — not a replacement for official advice.
        </div>

      </div>
    </main>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 28 }}>
      <h2 style={{ fontSize: 16, fontWeight: 500, color: '#111', marginBottom: 8 }}>{title}</h2>
      <p style={{ margin: 0 }}>{children}</p>
    </div>
  )
}
